Add pattern for query param name in HTTPQueryParamMatch
kubernetes-sigs/gateway-api pull request #1796
Opened 2023-03-09 01:55 UTC by gyohuangxin

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Add pattern for query param name in HTTPQueryParamMatch like other items' names to avoid illegal names.

**Which issue(s) this PR fixes**:

Fixes #1729 

**Does this PR introduce a user-facing change?**:

```release-note

```

2023-03-09 02:05 UTC, gyohuangxin commented
@shaneutt Can you review it? Thanks.

2023-03-12 17:58 UTC, gyohuangxin commented on apis/v1beta1/httproute_types.go
> +	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9!#$%&'*+\-.^_\x60|~]+$`
Yes, I pulled this pattern from other names properties likes:
https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1alpha2/httproute_types.go#L117
https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1beta1/httproute_types.go#L350
https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1alpha2/grpcroute_types.go#L414

2023-03-13 14:35 UTC, shaneutt approved these changes

2023-03-15 17:58 UTC, robscott reviewed
Thanks @gyohuangxin! One tiny nit but otherwise LGTM.

2023-03-15 17:58 UTC, robscott commented on apis/v1beta1/httproute_types.go
> +	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9!#$%&'*+\-.^_\x60|~]+$`
Can we use `HTTPHeaderName` as the type here instead of copying the regex? Would make this easier to maintain going forward.

2023-03-15 23:03 UTC, sunjayBhatia approved these changes
generally seems right, but agree with @robscott's idea to not have to repeat the same regex pattern many places, i don't know if adding another layer of type aliasing would be what we want to do/even work as we intend but that might be an idea to explore (e.g `GRPCHeaderName`, `HTTPHeaderName` and query param match `name` all use the same underlying more neutrally-named type)

2023-03-16 13:07 UTC, shaneutt commented
> Thanks for your comments. Agreed with @sunjayBhatia , the better solution is to introduce a shared type like `HeaderName` in `apis/v1beta1/shared_types.go` then any name properties (e.g `GRPCHeaderName`, `HTTPHeaderName` and `QueryParamMatchName`) can use them, so that we can reduce regular expression maintenance. @robscott @shaneutt What do you think?

Yep sgtm

2023-03-20 12:37 UTC, shaneutt requested changes

2023-03-20 12:37 UTC, shaneutt commented on apis/v1beta1/shared_types.go
> +// HeaderName is the name of an header or query parameter.
```suggestion
// HeaderName is the name of a header or query parameter.
```

2023-03-20 15:00 UTC, gyohuangxin commented on apis/v1beta1/shared_types.go
> +// HeaderName is the name of an header or query parameter.
@shaneutt Fixed, thanks.

2023-03-20 23:23 UTC, shaneutt approved these changes

2023-03-23 01:43 UTC, gyohuangxin commented
@robscott Could you review this? Thanks

2023-03-23 13:59 UTC, shaneutt approved these changes
Rob approved previously just with the caveat of the common type, we're all set thank you @gyohuangxin!!! :partying_face: 

/lgtm

2023-03-23 14:06 UTC, merged