Graduating GEP-726 (Path Redirects and Rewrites) to standard
kubernetes-sigs/gateway-api pull request #1874
Opened 2023-03-23 21:11 UTC by robscott

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This GEP has met the criteria for graduating to standard channel, as documented in https://github.com/kubernetes-sigs/gateway-api/issues/726#issuecomment-1419894406. This PR updates the GEP, documentation, and API types to reflect that.

**Which issue(s) this PR fixes**:
Fixes #726

**Does this PR introduce a user-facing change?**:
```release-note
GEP-726: Path Redirects and Rewrites has graduated to the standard channel.
```

/hold for consensus

2023-03-24 05:13 UTC, Xunzhuo reviewed
LGTM, thank!

2023-03-24 05:50 UTC, youngnick reviewed
/lgtm

/hold for multiple approval though.

2023-03-28 19:01 UTC, shaneutt requested changes

2023-03-28 19:01 UTC, shaneutt commented on apis/v1beta1/httproute_types.go
Looks like we have a couple places like this:

```go
// <gateway:experimental>
type HTTPPathModifier struct {
```

Where the type itself is marked as experimental, do we want to change those now?

2023-03-28 20:44 UTC, robscott commented
Good catch, thanks @shaneutt! Missed that the first time but removed now. Removing hold since I think we've had enough approvals, next LGTM should merge this.

/hold cancel

2023-03-28 20:45 UTC, robscott commented on apis/v1beta1/httproute_types.go
Updated, thanks! (Only found one place, let me know if I missed something).

2023-03-29 05:06 UTC, youngnick commented
/lgtm

2023-03-29 05:07 UTC, merged