rm EnableAllSupportedFeatures & add AllGatewayFeatures
kubernetes-sigs/gateway-api pull request #1907
Opened 2023-04-04 18:49 UTC by arkodg

* With https://github.com/kubernetes-sigs/gateway-api/pull/1878 the existing flag `EnableAllSupportedFeatures` used in implementations to run conformance tests pertaining to all Gateway/Ingress features will now also run Mesh conformance tests which might not be the intent.
* rm `EnableAllSupportedFeatures` and ask Ingress implementations to set `SupportedFeatures` to `AllGatewayFeatures` to achieve the same intent as before. Mesh implementations that also support Gateway features can set `SupportedFeatures` to `AllFeatures`.

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
the `EnableAllSupportedFeatures` flag has been removed. You can set `SupportedFeatures` to `AllGatewayFeatures` to run all tests related to Gateway/Ingress or you may set `SupportedFeatures` to `AllFeatures` to run all tests related to Gateway as well as Mesh

```

2023-04-04 22:27 UTC, arkodg commented
ptal @shaneutt

2023-04-05 00:21 UTC, sunjayBhatia requested changes
I don't think theres anything correlating the passed in string `AllGatewayFeatures` or `AllFeatures` to the right list of tests when using `go test ./conformance -supported-features=...`? Looks good when using your own suite but when using `go test` on the suite from this repo it only runs the tests from `StandardCoreFeatures`

2023-04-05 00:31 UTC, arkodg commented on conformance/utils/suite/features.go
>  // conformance tests with `all-features` flag.
good catch, will rm this

2023-04-05 00:39 UTC, arkodg commented
> I don't think theres anything correlating the passed in string `AllGatewayFeatures` or `AllFeatures` to the right list of tests when using `go test ./conformance -supported-features=...`? Looks good when using your own suite but when using `go test` on the suite from this repo it only runs the tests from `StandardCoreFeatures`

looks like some parse logic exists here https://github.com/kubernetes-sigs/gateway-api/blob/37768ab5b8a900b83fb989f4145789929983ca52/conformance/conformance_test.go#L72

2023-04-05 13:09 UTC, sunjayBhatia commented
> > I don't think theres anything correlating the passed in string `AllGatewayFeatures` or `AllFeatures` to the right list of tests when using `go test ./conformance -supported-features=...`? Looks good when using your own suite but when using `go test` on the suite from this repo it only runs the tests from `StandardCoreFeatures`
> 
> looks like some parse logic exists here
> 
> https://github.com/kubernetes-sigs/gateway-api/blob/37768ab5b8a900b83fb989f4145789929983ca52/conformance/conformance_test.go#L72

I tried it out and only StandardCoreFeatures tests are run, everything else is skipped

2023-04-05 13:09 UTC, sunjayBhatia commented
> > I don't think theres anything correlating the passed in string `AllGatewayFeatures` or `AllFeatures` to the right list of tests when using `go test ./conformance -supported-features=...`? Looks good when using your own suite but when using `go test` on the suite from this repo it only runs the tests from `StandardCoreFeatures`
> 
> looks like some parse logic exists here
> 
> https://github.com/kubernetes-sigs/gateway-api/blob/37768ab5b8a900b83fb989f4145789929983ca52/conformance/conformance_test.go#L72

I tried it out and only StandardCoreFeatures tests are run, everything else is skipped

2023-04-05 19:33 UTC, arkodg commented
> > > I don't think theres anything correlating the passed in string `AllGatewayFeatures` or `AllFeatures` to the right list of tests when using `go test ./conformance -supported-features=...`? Looks good when using your own suite but when using `go test` on the suite from this repo it only runs the tests from `StandardCoreFeatures`
> > 
> > 
> > looks like some parse logic exists here
> > https://github.com/kubernetes-sigs/gateway-api/blob/37768ab5b8a900b83fb989f4145789929983ca52/conformance/conformance_test.go#L72
> 
> I tried it out and only StandardCoreFeatures tests are run, everything else is skipped
> 
> ```
> $ go test -v -timeout=20m ./conformance -gateway-class=contour -supported-features=AllGatewayFeatures
> === RUN   TestConformance
>     conformance_test.go:54: Running conformance tests with contour GatewayClass
>          cleanup: true
>          debug: false
>          supported features: [AllGatewayFeatures]
>          exempt features: []
> ...
> === RUN   TestConformance/HTTPRouteCrossNamespace
>     suite.go:200: Skipping HTTPRouteCrossNamespace: suite does not support HTTPRoute
> === RUN   TestConformance/HTTPRouteDisallowedKind
>     suite.go:200: Skipping HTTPRouteDisallowedKind: suite does not support HTTPRoute
> ...
> ```
> 
> `AllGatewayFeatures` is parsed but when we filter tests that does not actually result in any tests being run outside of `StandardCoreFeatures` which are added by default:
> 
> * https://github.com/kubernetes-sigs/gateway-api/blob/26ce3a32c8c7b27a918961cf208df07dbda08e25/conformance/utils/suite/suite.go#L201-L205
> * https://github.com/kubernetes-sigs/gateway-api/blob/228104ab87f6514aec24cf17796888ce92a1391c/conformance/utils/suite/suite.go#L91-L95

thanks for pointing this out. If support for the `supported-features` flag is broken on main, imo, would be better to raise a separate issue and tackle it in a another PR

2023-04-05 19:54 UTC, sunjayBhatia commented
> thanks for pointing this out. If support for the `supported-features` flag is broken on main, imo, would be better to raise a separate issue and tackle it in a another PR

This is specific to the added new features. This PR adds two new feature "sets" that can be used when you're writing your own suite, but the new feature names are not actually respected when using `-supported-features`. Yes they are passed through but this is a problem because no tests are actually tagged with `AllGatewayFeatures` or `AllFeatures` (because these new "features" are a collection of features). When a user does `-supported-features=AllFeatures` if we don't want to tag every test with `AllFeatures`, then we need to add (in this change) something that translates that passed in string to a set of tests for the suite to run, otherwise the suite logic from here will just run `StandardCoreFeatures`: https://github.com/kubernetes-sigs/gateway-api/blob/228104ab87f6514aec24cf17796888ce92a1391c/conformance/utils/suite/suite.go#L89-L95

2023-04-05 20:06 UTC, arkodg commented
> > thanks for pointing this out. If support for the `supported-features` flag is broken on main, imo, would be better to raise a separate issue and tackle it in a another PR
> 
> This is specific to the added new features. This PR adds two new feature "sets" that can be used when you're writing your own suite, but the new feature names are not actually respected when using `-supported-features`. Yes they are passed through but this is a problem because no tests are actually tagged with `AllGatewayFeatures` or `AllFeatures` (because these new "features" are a collection of features). When a user does `-supported-features=AllFeatures` if we don't want to tag every test with `AllFeatures`, then we need to add (in this change) something that translates that passed in string to a set of tests for the suite to run, otherwise the suite logic from here will just run `StandardCoreFeatures`:
> 
> https://github.com/kubernetes-sigs/gateway-api/blob/228104ab87f6514aec24cf17796888ce92a1391c/conformance/utils/suite/suite.go#L89-L95


seeing this issue on `main` w/o this PR change
```
git log -n1
commit ccc922b1f186d519fcab9a2c430864a3b60e63ca (HEAD -> main, upstream/main)
Merge: 8dde5080 2acae499
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Tue Apr 4 09:53:42 2023 -0700

    Merge pull request #1894 from shaneutt/shaneutt/mesh-conformance-machinery-patch
    
    Conformance Tests: No implicit test runs without features

🐳 ~/go-workspace/src/github.com/kubernetes-sigs/gateway-api/conformance$ go test -v ./conformance_test.go -args -gateway-class=envoy-gateway -supported-features=AllFeatures debug=true
=== RUN   TestConformance
    conformance_test.go:54: Running conformance tests with envoy-gateway GatewayClass
         cleanup: true
         debug: false
         enable all features: false 
         supported features: [AllFeatures]
         exempt features: []
........
=== RUN   TestConformance/HTTPRouteQueryParamMatching
    suite.go:203: Skipping HTTPRouteQueryParamMatching: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteRedirectHostAndStatus
    suite.go:203: Skipping HTTPRouteRedirectHostAndStatus: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteRedirectPath
    suite.go:203: Skipping HTTPRouteRedirectPath: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteRedirectPort
    suite.go:203: Skipping HTTPRouteRedirectPort: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteRedirectScheme
    suite.go:203: Skipping HTTPRouteRedirectScheme: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteReferenceGrant
    suite.go:203: Skipping HTTPRouteReferenceGrant: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteRequestHeaderModifier
    suite.go:203: Skipping HTTPRouteRequestHeaderModifier: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteResponseHeaderModifier
    suite.go:203: Skipping HTTPRouteResponseHeaderModifier: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteRewriteHost
    suite.go:203: Skipping HTTPRouteRewriteHost: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteRewritePath
    suite.go:203: Skipping HTTPRouteRewritePath: suite does not support HTTPRoute
=== RUN   TestConformance/HTTPRouteSimpleSameNamespace
    suite.go:203: Skipping HTTPRouteSimpleSameNamespace: suite does not support HTTPRoute
=== RUN   TestConformance/MeshBasic
    suite.go:203: Skipping MeshBasic: suite does not support Mesh
=== RUN   TestConformance/MeshTrafficSplit
    suite.go:203: Skipping MeshTrafficSplit: suite does not support Mesh
=== RUN   TestConformance/TLSRouteSimpleSameNamespace
    suite.go:203: Skipping TLSRouteSimpleSameNamespace: suite does not support TLSRoute
```

2023-04-05 20:51 UTC, sunjayBhatia commented
> seeing this issue on `main` w/o this PR change

right, the `-all-features` flag covered that use case before, now that is taken away there is no way to run all the features in the suite via `go test` or `AllGatewayFeatures`

2023-05-03 12:26 UTC, shaneutt reviewed
So I don't mean to put a damper on this PR, but since this isn't making it into `v0.7.0` anyway, and it's looking likely that `v0.8.0` will actually just get collided into `v1.0.0` where _we will have conformance profiles which enable subscribing to large groups of tests_ maybe we can pass on this one for now? Or is there some really strong need I'm misunderstanding?

/hold

2023-05-03 17:24 UTC, arkodg commented
closing since its not needed but a good to have

2023-05-03 17:24 UTC, closed without merging