doc: Add Amazon EKS to the list of implementations
kubernetes-sigs/gateway-api pull request #1916
Opened 2023-04-05 22:33 UTC by liwenwu-amazon

**What type of PR is this?**

Add one of the following kinds:

/kind documentation

**What this PR does / why we need it**:

AWS Gateway API Controller is a new implementation of the Gateway API that may be of interest to the wider audience of the Gateway API project. 

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note

```

2023-04-05 23:09 UTC, robscott commented
Thanks @liwenwu-amazon!

/lgtm
/approve

2023-04-05 23:09 UTC, robscott commented
/ok-to-test

2023-04-05 23:10 UTC, shaneutt requested changes
Couple small things, then looks good! Glad to have you join the implementations page :partying_face:

2023-04-05 23:10 UTC, shaneutt commented on site-src/implementations.md
> +
```suggestion
```

2023-04-05 23:10 UTC, shaneutt commented on site-src/implementations.md
> +
```suggestion
```

2023-04-05 23:10 UTC, shaneutt commented on site-src/implementations.md
> +[23]:#amazon-kubernetes-service
```suggestion
[23]:#amazon-elastic-kubernetes-service
```

2023-04-05 23:10 UTC, shaneutt commented on site-src/implementations.md
> +
```suggestion
```

2023-04-05 23:10 UTC, shaneutt commented on site-src/implementations.md
> +
:+1:

2023-04-05 23:10 UTC, shaneutt commented on site-src/implementations.md
> +
```suggestion
```

2023-04-05 23:15 UTC, merged

2023-04-06 13:18 UTC, shaneutt commented
This auto-merged through my request for changes, which included a fix for the link for EKS so I've created a follow-up https://github.com/kubernetes-sigs/gateway-api/pull/1921