docs(site-src): update the example for the matches
kubernetes-sigs/gateway-api pull request #2185
Opened 2023-07-14 03:42 UTC by saltbo

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
update the matches example to avoid misunderstanding

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2023-07-14 13:54 UTC, sunjayBhatia commented on site-src/api-types/httproute.md
> +        values:
header match should be a list with at least header name and value as explicit fields (not a map like here), see https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPHeaderMatch

2023-07-14 13:56 UTC, sunjayBhatia requested changes
left a comment on fixing the header match section

2023-07-17 20:17 UTC, robscott commented
Thanks @saltbo!

/lgtm
/approve

2023-07-17 20:19 UTC, sunjayBhatia approved these changes

2023-07-17 20:31 UTC, merged