Fix conformance test flags are exported to other libraries that use the conformance test suite
kubernetes-sigs/gateway-api pull request #2843
Opened 2024-03-05 03:21 UTC by hanxiaop

**What type of PR is this?**

**What this PR does / why we need it**:

/kind bug
/area conformance

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2841

**Does this PR introduce a user-facing change?**:

```release-note

```

2024-03-07 01:50 UTC, hanxiaop commented
@keithmattix @kflynn can you PTAL when you get a chance? Thanks!

2024-03-13 03:33 UTC, hanxiaop commented
Also cc @LiorLieberman to take a look, the feature was introducted in https://github.com/istio/istio/pull/48770.

2024-03-13 07:32 UTC, LiorLieberman commented
Thanks @hanxiaop! 
Can you elaborate on the problem? I am not sure I understand

2024-03-13 07:56 UTC, hanxiaop commented
> Thanks @hanxiaop! Can you elaborate on the problem? I am not sure I understand

@LiorLieberman So basically, in that PR, you imported the test suite code into the product code:

https://github.com/istio/istio/blob/42572fab5be79af8de284953ec72cbf439631da8/pilot/pkg/config/kube/gateway/supported_features.go#L24,

and after https://github.com/kubernetes-sigs/gateway-api/pull/2801/files#diff-3532d0dde2d46785ab138cfe0fa7bddc5c1901dde4fe4079880451c010ea8254R34, the flag package was also imported into the suite. After that, our command-line tool was filled with gateway conformance test flags alongside our own pflags, since the test flags were imported in the dependency and thus in the flag set. This PR moves the features file out of the suite, so that we can directly import the features instead of the entire suite package and avoid issues like flags being altered.

2024-03-13 14:31 UTC, dprotaso commented
cc @mlavacca - since you're refactoring the experimental suite

2024-03-13 14:59 UTC, howardjohn commented
> Thanks, I think many implementations uses suite to import features. This would require all of them to move to features or their code wont work.



If we really want to maintain Go-level compatibility (which I think is a non-goal of the project, but I could be wrong) we can always add a type alias in `suite`.

2024-03-14 01:48 UTC, hanxiaop commented on hack/supportedfeatures/main.go
> +	"sigs.k8s.io/gateway-api/conformance/utils/features"
Great suggestion! Fixed.

2024-03-14 01:53 UTC, hanxiaop commented
> Not sure whats the procedure in such case and whether it is considered breaking change or not. /cc @youngnick @shaneutt @robscott

I think this will not be an issue or a breaking change, as it's fairly common for bumping a dependency to result in a change in the package path.

2024-03-14 14:50 UTC, mlavacca reviewed
This looks good to me, @hanxiaop! Would you mind if we wait for https://github.com/kubernetes-sigs/gateway-api/pull/2868 to land before merging this one (that's part of the conformance suite epic and is required for 1.1)?

2024-03-15 01:45 UTC, hanxiaop commented
> This looks good to me, @hanxiaop! Would you mind if we wait for #2868 to land before merging this one (that's part of the conformance suite epic and is required for 1.1)?

@mlavacca no problem, I'll rebase once it's merged, thanks for the review!

2024-03-29 06:31 UTC, hanxiaop commented
@mlavacca PTAL, thanks!

2024-03-29 10:20 UTC, mlavacca commented
> > > Thanks @hanxiaop! Can you elaborate on the problem? I am not sure I understand
> > 
> > 
> > @LiorLieberman So basically, in that PR, you imported the test suite code into the product code:
> > https://github.com/istio/istio/blob/42572fab5be79af8de284953ec72cbf439631da8/pilot/pkg/config/kube/gateway/supported_features.go#L24,
> > and after https://github.com/kubernetes-sigs/gateway-api/pull/2801/files#diff-3532d0dde2d46785ab138cfe0fa7bddc5c1901dde4fe4079880451c010ea8254R34, the flag package was also imported into the suite. After that, our command-line tool was filled with gateway conformance test flags alongside our own pflags, since the test flags were imported in the dependency and thus in the flag set. This PR moves the features file out of the suite, so that we can directly import the features instead of the entire suite package and avoid issues like flags being altered.
> 
> Thanks, I think many implementations uses `suite` to import features. This would require all of them to move to `features` or their code wont work.
> 
> Not sure whats the procedure in such case and whether it is considered breaking change or not. /cc @youngnick @shaneutt @robscott

Many changes have been made to the suite for its graduation; implementations will have to adapt to those changes in any case when bumping to the next Gateway API version. I do not see this kind of change as problematic.

2024-03-29 10:24 UTC, mlavacca requested changes
We need to change all the references to the features in the actual tests, under `conformance/tests`. As it is, the code does not even compile.

2024-04-01 02:38 UTC, hanxiaop commented
> We need to change all the references to the features in the actual tests, under `conformance/tests`. As it is, the code does not even compile.

@mlavacca Fixed, missed that dependency. It would be great if someone could add the `ok-to-test` label so I can check if there are more things being broken.

2024-04-08 02:55 UTC, hanxiaop commented
@mlavacca @youngnick @shaneutt @robscott @howardjohn @keithmattix PTAL, thanks!

2024-04-12 20:16 UTC, howardjohn approved these changes
/lgtm

can you rebase?

2024-04-14 02:33 UTC, hanxiaop commented
@howardjohn PTAL again, thanks!

2024-04-15 15:14 UTC, howardjohn approved these changes
/lgtm

2024-04-16 01:43 UTC, hanxiaop commented
@robscott PTAL, thanks!

2024-04-16 01:55 UTC, howardjohn commented
/lgtm

2024-04-16 18:27 UTC, robscott commented
Thanks @hanxiaop!

/approve

2024-04-16 21:46 UTC, robscott commented
/ok-to-test
/release-note-none

2024-04-16 23:01 UTC, robscott commented
@hanxiaop if you'd prefer we can use #2980 which copied this PR and made some modifications to pass presubmits.

2024-04-17 01:53 UTC, hanxiaop commented
> @hanxiaop if you'd prefer we can use #2980 which copied this PR and made some modifications to pass presubmits.

@robscott Thanks! I think it should be good now. New tests are continually being added to the folder, so I need to do a rebase again. If it doesn't work I think we can use that PR.

2024-04-17 02:11 UTC, hanxiaop commented
@howardjohn just rebased and can you LGTM again? Thanks!

2024-04-17 16:08 UTC, howardjohn commented
/lgtm

2024-04-17 16:34 UTC, merged