Update geps/overview.md - fix a broken link in geps/overview.md
kubernetes-sigs/gateway-api pull request #3386
Opened 2024-10-10 01:01 UTC by joerober

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
This fixes a broken link in geps/overview.md file. 

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2024-10-10 02:50 UTC, kflynn commented
@joerober Hey, thanks for looking into this! That said -- if I look at https://gateway-api.sigs.k8s.io/geps/overview/, the "graduation criteria" link works for me. Can you doublecheck? or let us know what browser and such you're having an issue with?

2024-10-10 13:41 UTC, kflynn commented
@joerober Ah, I get it. You're viewing the source directly, rather than the rendered pages -- the links are constructed to do the right thing when viewed from the Gateway API website, and it does work from https://gateway-api.sigs.k8s.io/geps/overview/ as it should.

🤔 I don't know of a way to build these so that the links work from both (in the rendered version, this is no longer a Markdown file, so linking directly to the `.md` isn't appropriate). Any suggestions for how we might better point people looking at the sources to the rendered pages?

2024-10-10 13:42 UTC, kflynn requested changes
This will break the rendered page on the website, as described above, so we need to find a different answer here. 🙂

2024-10-10 13:42 UTC, kflynn commented
/hold

just in case. 🙂

2024-10-10 19:18 UTC, joerober commented
@kflynn  Documentation is within Gateway API developer guide: https://gateway-api.sigs.k8s.io/contributing/devguide/#documentation  

You are correct that my edit breaks the page. I now see that there is a 'deploy/netlify - Deploy Preview ready!' within this PR (I had to scroll to the bottom of 'All checks') 

I'll look at this with the mkdocs live preview server (as described in guide) to if or how to fix in both source and rendered pages.

2025-02-12 22:46 UTC, shaneutt commented
Sounds like there's nothing to do here just now so I'll consider this one closed,

/close

However, please feel free to re-open when you're ready!

2025-02-12 22:46 UTC, closed without merging