Spelling
kubernetes-sigs/gateway-api pull request #3400
Opened 2024-10-21 17:33 UTC by jsoref

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/gateway-api/actions/runs/11444311412#summary-31838911907

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/gateway-api/actions/runs/11444311702#summary-31838912845

It also fixes the labels of a pair of images to match the word actually used

**Which issue(s) this PR fixes**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

2024-10-21 17:45 UTC, jsoref commented on RELEASE.md
> +- Update the implementation table path (`nav.Implementations.Comparison`) in the nav of `mkdocs.yml` to point to the latest release file (for example Implementation Comparison points to `implementati
I'm not sure about this one...

2024-10-21 17:45 UTC, jsoref commented on apis/v1/util/validation/gatewayclass_test.go
> +	validationutil "sigs.k8s.io/gateway-api/apis/v1beta1/util/validation"
this makes it consistent w/ another user...

2024-10-21 17:45 UTC, jsoref commented on conformance/utils/suite/suite_test.go
> +	coreFeature     features.FeatureName = "coreFeature"
this was odd... I hope it doesn't matter

2024-10-21 17:45 UTC, jsoref commented on geps/gep-1364/index.md
> +conformance, and make it a feature that implementations may opt into - making it
People often complain about this change. I haven't merged `opt in`+`to` much in this PR. I'm happy to drop this or anything else.

2024-10-21 17:45 UTC, jsoref commented on geps/gep-1762/metadata.yaml
> +  - frankbu
notable correction

2024-10-21 17:45 UTC, jsoref commented on geps/gep-724/images/724-alt1.png
https://github.com/kubernetes-sigs/gateway-api/pull/725#pullrequestreview-2373392268

2024-10-21 17:45 UTC, jsoref commented on geps/gep-724/index.md
> +Foo in resources of kind Bar. Names and section names are intentionally
this is notable

2024-10-21 17:45 UTC, jsoref commented on geps/overview.md
> +  * **Prototyping:** An optional extension of `Provisional` in
Notable

2024-10-21 17:45 UTC, jsoref commented on hack/invalid-examples/standard/httproute/invalid-httpredirect-hostname.yaml
Afaict, this file isn't referenced anywhere...
```diff
-hack/invalid-examples/standard/httproute/invalid-httredirect-hostname.yaml
+hack/invalid-examples/standard/httproute/invalid-httpredirect-hostname.yaml
```

2025-01-19 19:22 UTC, jsoref commented
/remove-lifecycle stale

2025-02-11 18:47 UTC, shaneutt requested changes
Thanks for the thorough once over of the repositories spelling errors!

I read it all over, and everything here looks good to me _except_ for historical GEP images which were accurate at the time (see comments below).

It occurred to me that would be nice if we could add checks that can run in CI to avoid these getting merged in the first place (however, that doesn't need to be the burden of this PR).

2025-02-11 21:10 UTC, jsoref commented on geps/gep-724/images/724-alt1.png
That's fine. It was an interesting challenge.

2025-02-11 21:11 UTC, jsoref commented
I'm happy to provide a version of this for CI after a version of this merges. It's used by a number majors projects. I'm happy to talk about that on slack/in an issue after this merges.

2025-02-12 12:43 UTC, shaneutt commented on geps/gep-724/images/724-alt1.png
Thank you for the effort, sorry that it caused you some work. Appreciate the understanding!

2025-02-12 17:46 UTC, robscott commented
Thanks @jsoref!

/lgtm

2025-02-12 18:32 UTC, merged